export const TOY_BROWSE_REQUEST = "TOY_BROWSE_REQUEST";
export const TOY_BROWSE_SUCCESS = "TOY_BROWSE_SUCCESS";
export const TOY_BROWSE_FAIL = "TOY_BROWSE_FAIL";

export const TOY_DETAIL_REQUEST = "TOY_DETAIL_REQUEST";
export const TOY_DETAIL_SUCCESS = "TOY_DETAIL_SUCCESS";
export const TOY_DETAIL_FAIL = "TOY_DETAIL_FAIL";

export const TOY_POST_REQUEST = "TOY_POST_REQUEST";
export const TOY_POST_SUCCESS = "TOY_POST_SUCCESS";
export const TOY_POST_FAIL = "TOY_POST_FAIL";

export const TOY_EDIT_REQUEST = "TOY_EDIT_REQUEST";
export const TOY_EDIT_SUCCESS = "TOY_EDIT_SUCCESS";
export const TOY_EDIT_FAIL = "TOY_EDIT_FAIL";

export const TOY_DELETE_REQUEST = "TOY_DELETE_REQUEST";
export const TOY_DELETE_SUCCESS = "TOY_DELETE_SUCCESS";
export const TOY_DELETE_FAIL = "TOY_DELETE_FAIL";

export const TOY_IMAGE_UPLOAD = "TOY_IMAGE_UPLOAD";
export const TOY_IMAGE_UPLOAD_FAIL = "TOY_IMAGE_UPLOAD_FAIL";

export const TOY_DONE_CHANGE_DIR = "TOY_DONE_CHANGE_DIR";
